SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[refreshTokens](
	[jti] [varchar](100) NOT NULL,
	[linkedUserId] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[refreshTokens] ADD  CONSTRAINT [PK_refreshTokens] PRIMARY KEY CLUSTERED 
(
	[jti] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_refreshTokens_linkedUserId] ON [dbo].[refreshTokens]
(
	[linkedUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[refreshTokens]  WITH CHECK ADD  CONSTRAINT [FK_refreshTokens_AppUsers_linkedUserId] FOREIGN KEY([linkedUserId])
REFERENCES [dbo].[AppUsers] ([uid])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[refreshTokens] CHECK CONSTRAINT [FK_refreshTokens_AppUsers_linkedUserId]
GO
