SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[menuplan](
	[date] [datetime2](7) NOT NULL,
	[meal] [varchar](250) NULL,
	[dessert] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[menuplan] ADD  CONSTRAINT [PK_menuplan] PRIMARY KEY CLUSTERED 
(
	[date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
